import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
import Provider from '@/components/providers/provider'
import {ToastContainer} from '@/components/home_utility/toastify/Toastify';
import  connect  from '@/backend/dbConnection/db'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang='eng'>
      <body className={inter.className}>
      <ToastContainer position="top-left"/>
      <Provider>
      <div className='containerlayout'>
      <Navbar/>
      <div className='maincontent'>
      {children}
      </div>
      <Footer/>
      </div>
      </Provider>
      </body>
      </html>
    
  )
}
