import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/providers/provider";
import connect from "@/backend/dbConnection/db";
import Uiprovider from "@/components/providers/uiprovider";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "LinkTree ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  connect();
  return (
    <html lang="eng">
      <body className={inter.className}>
    <Provider>
    <Uiprovider>
      <div>
     {children}
     </div>
     </Uiprovider>
    </Provider>
      </body>
    </html>
  );
}
