import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import Provider from "@/components/providers/provider";
import connect from "@/backend/dbConnection/db";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LinkTree ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  connect();
  return (
    <html lang="eng">
      <body className={inter.className}>
      <div className="bodycontainer">
    <Provider>
      <div>
     {children}
     </div>
    </Provider>
      </div>
      </body>
    </html>
  );
}
